name: C/C++ CI

on:
  push:
    branches-ignore: [ ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: docker
    container:
      image: node:22-bookworm

    steps:
    - name: Set up build requirements
      run: apt-get update -y && apt-get install -y cmake g++

    - name: Install LimeSuite dependencies
      run: apt-get update -y && apt-get install -y limesuite liblimesuite-dev

    - name: Install HDF5 dependencies
      run: apt-get update -y && apt-get install -y libhdf5-dev
    
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build
      run: cmake -S . -B build && cmake --build build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
