name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # Install LimeSuite
    - name: Install LimeSuite dependencies
      run: sudo apt-get update -y && sudo apt-get install -y limesuite liblimesuite-dev

    # Install H5c++
    - name: Install HDF5 dependencies
      run: sudo apt-get update -y && sudo apt-get install -y libhdf5-dev
    
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
