name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install LimeSuite dependencies
      run: sudo apt-get update -y && sudo apt-get install -y limesuite liblimesuite-dev

    - name: Install HDF5 dependencies
      run: sudo apt-get update -y && sudo apt-get install -y libhdf5-dev
    
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: actions/setup-cmake@v1
      with:
        cmake-version: '3.28.1'

    - name: Build
      run: cmake -S . -B build && cmake --build build
    